info:
  relay_url: wss://nostr01.vida.dev
  relay_root_redirect_url: https://vida.page/nostr
  name: nostr01.vida.dev  
  description: Vida Nostream Relay
  pubkey: 42b3db1ca9f73ea861cca1f5a9f74dadf97b6ff539cdf722ccae16119907dfe6
  contact: team@vida.live
payments:
  enabled: true
  processor: vida
  feeSchedules:
    admission:
    - enabled: true
      descripton: Admission fee charged per public key in msats (1000 msats = 1 satoshi)
      amount: 1000000
      whitelists:
        pubkeys:
          - replace-with-your-pubkey-in-hex
          # Allow the following Zap providers:
          # LightningTipBot by Calle
          - "fcd720c38d9ee337188f47aac845dcd8f590ccdb4a928b76dde18187b4c9d37d"
          # Vida Global Zaps
          - "42b3db1ca9f73ea861cca1f5a9f74dadf97b6ff539cdf722ccae16119907dfe6"
    publication:
    - enabled: true
      descripton: Per event fee charged per public key in msats (1000 msats = 1 satoshi)
      amount: 10000
      whitelists:
        pubkeys:
        - "42b3db1ca9f73ea861cca1f5a9f74dadf97b6ff539cdf722ccae16119907dfe6"
webhooks:
  pubkeyChecks: true
  topUps: true
  eventChecks: false
  eventCallbacks: false
  endpoints:
    baseURL: https://api.vida.dev/
    pubkeyCheck: nostream/pubkeyAdmit
    eventCheck: nostream/eventCheck
    topUps: nostream/topUp
    eventCallback: nostream/eventCallback
paymentsProcessors:
  vida:
    baseURL: https://api.vida.dev/
    callbackBaseURL: https://nostr01.vida.dev/callbacks/zebedee
    ipWhitelist:
      - "3.225.112.64"
      - "::ffff:3.225.112.64"
  lnbits:
    baseURL: https://lnbits.your-domain.com/
    callbackBaseURL: https://nostream.your-domain.com/callbacks/lnbits
network:
  maxPayloadSize: 524288
  remoteIpHeader: x-forwarded-for
workers:
  count: 16
mirroring:
  static: []
limits:
  invoice:
    rateLimits:
    - period: 60000
      rate: 6
    - period: 3600000
      rate: 16
    ipWhitelist:
    - "::1"
    - "10.10.10.1"
    - "::ffff:10.10.10.1"
  connection:
    rateLimits:
    - period: 1000
      rate: 12
    - period: 60000
      rate: 48
    - period: 3600000
      rate: 300
    ipWhitelist:
    - "::1"
    - "10.10.10.1"
    - "::ffff:10.10.10.1"
  event:
    eventId:
      minLeadingZeroBits: 0
    kind:
      whitelist: []
      blacklist: []
    pubkey:
      minBalance: 0
      topUp: 1000000
      minLeadingZeroBits: 0
      whitelist: []
      blacklist: []
    createdAt:
      maxPositiveDelta: 900
      maxNegativeDelta: 0
    content:
    - description: 64 KB for event kind ranges 0-10 and 40-49
      kinds:
      - - 0
        - 10
      - - 40
        - 49
      maxLength: 65536
    - description: 96 KB for event kind ranges 11-39 and 50-max
      kinds:
      - - 11
        - 39
      - - 50
        - 9007199254740991
      maxLength: 98304
    rateLimits:
    - description: 6 events/min for event kinds 0, 3, 40 and 41
      kinds:
      - 0
      - 3
      - 40
      - 41
      period: 60000
      rate: 6
    - description: 12 events/min for event kinds 1, 2, 4 and 42
      kinds:
      - 1
      - 2
      - 4
      - 42
      period: 60000
      rate: 12
    - description: 360 events/hour for event kinds 1, 2, 4 and 42
      kinds:
      - 1
      - 2
      - 4
      - 42
      period: 3600000
      rate: 360
    - description: 30 events/min for event kind ranges 5-7 and 43-49
      kinds:
      - - 5
        - 7
      - - 43
        - 49
      period: 60000
      rate: 30
    - description: 24 events/min for replaceable events and parameterized replaceable
        events
      kinds:
      - - 10000
        - 19999
      - - 30000
        - 39999
      period: 60000
      rate: 24
    - description: 60 events/min for ephemeral events
      kinds:
      - - 20000
        - 29999
      period: 60000
      rate: 60
    - description: 720 events/hour for all events
      period: 3600000
      rate: 720
    - description: 2880 events/day for all events
      period: 86400000
      rate: 2880
    whitelists:
      pubkeys: []
      ipAddresses:
      - "::1"
      - "10.10.10.1"
      - "::ffff:10.10.10.1"
  client:
    subscription:
      maxSubscriptions: 10
      maxFilters: 10
  message:
    rateLimits:
    - description: 600 raw messages/min
      period: 60000
      rate: 600
    - description: 36000 raw messages/hour
      period: 3600000
      rate: 36000
    ipWhitelist:
    - "::1"
    - "10.10.10.1"
    - "::ffff:10.10.10.1"
